require('lazy').setup({
  require('plugins.colorscheme'),
  require('plugins.mini'),
  require('plugins.dev'),
  require('plugins.git'),
  require('plugins.treesitter'),
  require('plugins.lsp'),
  require('plugins.terraform'),
})
